### ISSUE TITLE
Can I change the color and size of cells ???

### ISSUE THREAD

**Issue by alexssdd** [codemix/yii2-excelexport#1]
Сan you add an example of changing the color or size of the cell.

**Comment by mikehaertl** [comment]
I've not done that myself yet. But you have access to the `PHPExcel` instance from `$file->getWorkbook()`. Then you can access each sheet and cell as described in the PHPExcel documentation:

https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#styles

You can also define callbacks for each column in the `callbacks` key in `sheets`. The format is the same as in `titles` (`[ 'A' => function(){}, 'B' => ...]`). The callback function will receive the `PHPExcel_Cell` object and the current row and column index. See https://github.com/codemix/yii2-excelexport/blob/master/src/ExcelSheet.php#L124

**Comment by mikehaertl** [comment]
Ok, I've tried now and updated the README accordingly. Check here:

https://github.com/codemix/yii2-excelexport#styling

**Comment by alexssdd** [comment]
Thanks!
