### ISSUE TITLE
Improvement: Separate sheet generation from create file

### ISSUE THREAD

**Issue by AirSeeker** [codemix/yii2-excelexport#10]
I encountered a problem when you need to have access to a particular sheet in multi sheet excel file. I had to combine rows and columns for different sheets. For this I had to use mergeCells method of object PHPExcel. And for each sheet call method mergeCells. Lets maybe separeta sheet generation from file create. So you can call $file->generateSheets(); and then foreach sheet $file->getWorkbook()->getSheet($currentSheet)->mergeCells($mergeArea);

    /**
     * Create the Excel file and save it to the temp file
     */
    protected function createFile()
    {
        if (!$this->_created) {
            $this->generateSheets();
            $this->getWriter()->save((string)$this->getTmpFile());
            $this->_created = true;
        } else {
            $this->getWriter()->save((string)$this->getTmpFile());
        }
    }

    /**
     * Generate Excel Sheets
     * @throws \Exception
     */
    public function generateSheets()
    {
        $workbook = $this->getWorkbook();
        $i = 0;
        foreach ($this->sheets as $title => $config) {
            if (is_string($config)) {
                $config = ['class' => $config];
            } elseif (is_array($config)) {
                if (!isset($config['class'])) {
                    $config['class'] = ExcelSheet::className();
                }
            } elseif (!is_object($config)) {
                throw new \Exception('Invalid sheet configuration');
            }
            $sheet = (0 === $i++) ? $workbook->getActiveSheet() : $workbook->createSheet();
            if (is_string($title)) {
                $sheet->setTitle($title);
            }
            Yii::createObject($config, [$sheet])->render();
        }
        $this->_created = true;
    }

**Comment by mikehaertl** [comment]
@AirSeeker Agree, this seems to make sense. Any reason why we shouldn't call it `createSheets()` though? Just to be more constistent with `createFile()`.

**Comment by AirSeeker** [comment]
Yes. createSheets() sounds great to me.

**Comment by mikehaertl** [comment]
@AirSeeker I've committed the change to master but had no time to test it. Could you help out here? I'd create a new 2.2.0 release right after your confirmation.

**Comment by AirSeeker** [comment]
Sheets in Excel start from 0 pointer. In previous version you have
`$sheet = (0 === $i++) ? $workbook->getActiveSheet() : $workbook->createSheet();`
that was correct because you start from 0.
now you have 
`$i++;$sheet = ($i === 0) ?$workbook->getActiveSheet() : $workbook->createSheet();`
so now you always start from 1. It always creates a blank first sheet.

Icrement in line 136 must be moved before 142 line.
https://github.com/codemix/yii2-excelexport/blob/master/src/ExcelFile.php#L136
https://github.com/codemix/yii2-excelexport/blob/master/src/ExcelFile.php#L142

**Comment by mikehaertl** [comment]
Ah right, sorry. I though't I'd make the code a bit clearer and instead introduced this stupid bug. I've pushed a fix.

**Comment by AirSeeker** [comment]
Tested. Allworks. Thanks.

**Comment by mikehaertl** [comment]
Just released 2.2.0 including this new feature. Thanks for your help!
