### ISSUE TITLE
width column

### ISSUE THREAD

**Issue by SkyZhenya** [codemix/yii2-excelexport#11]
How to set width for column ??

**Comment by AirSeeker** [comment]
You can set it from callbacks  or use PHPExcel object
$file->getWorkbook()->getSheet($sheetNumberStartFromZero)->getColumnDimension('A')->setWidth("50");

**Comment by mikehaertl** [comment]
For questions like this please also consult the PHPOffice documentation and their wiki: 

* https://github.com/PHPOffice/PHPExcel/tree/develop/Documentation/markdown/Overview
* https://github.com/PHPOffice/PHPExcel/wiki

**Comment by shabaz-ejaz** [comment]
Its not clear in your documentation how to set the cell width. You show a few examples of how to use the `styles ` array: 

`'styles' => [
                'A1:Z1000' => [
                    'font' => [
                        'bold' => true,
                        'color' => ['rgb' => 'FF0000'],
                        'size' => 15,
                        'name' => 'Verdana'
                    ]
                    'alignment' => [
                        'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_RIGHT,
                    ],
                ],
            ],`

But it's not clear how to add more properties to this, we can't consult the PHPOffice docs as this is a wrapper around the object so the syntax is not going to be the same.

Can you show an example of how to achieve this using the  `styles` array?

**Comment by mikehaertl** [comment]
@shabaz001 I think, you can't set a column width via `styles` in PHPExcel.

But you can use the method described in the PHPExcel documentation: https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#setting-a-columns-width

This should work, but maybe you first have to call `$file->createSheets()` (couldn't test and don't remember right now):

```
$file
    ->getWorkbook()
    ->getActiveSheet()
    ->getColumnDimension('D')
    ->setWidth(12);
```

What you set in `styles` uses the same syntax as PHPExcel. See here: https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#formatting-cells.

The array keys like `font`, `alignment`, etc. seem to correspond to the respective getter/setter (`setFont()`, `setAlignment()`, etc.).
