### ISSUE TITLE
Implement ability to apply data from array

### ISSUE THREAD

**Issue by AirSeeker** [codemix/yii2-excelexport#12]
With large amount of data, in my case its 30 sheets with about 1000 rows and 80 columns. The time to generate excel file is huge. I investigated that time can be twice faster if use method fromArray. Lets add parameter insertRawData. If insertRawData true then add data to sheets by fromArray method.
In model:

        $file = \Yii::createObject([
            'class' => 'codemix\excelexport\ExcelFile',
            'insertRawData' => true,
            'sheets' => $sheetsData
        ]);

Also about styles like: callbacks, format , formatters and types. In order to apply style lets add additional parameter stylesRules for each sheet. It can be applied to sheet by applyFromArray method.
For example:

            $sheetsData["sheet title"] = [
                'data' => $data,
                'stylesRules' => [
                    'A1:Z1000' => [
                        'font' => [
                            'bold' => true,
                            'color' => ['rgb' => 'FF0000'],
                            'size' => 15,
                            'name' => 'Verdana'
                        ]
                    ]
                ]
            ];

And in ExcelSheet:

    /**
     * Render the data for hole sheet
     */
    protected function renderSheet()
    {
        $this->_sheet->fromArray($this->getData());
        $stylesRules = $this->getStylesRules();
        foreach ($stylesRules as $range => $rule) {
            $this->_sheet->getStyle($range)->applyFromArray($rule);
        }
    }

    public function getStylesRules()
    {
        return $this->_stylesRules;
    }

    public function setStylesRules(array $stylesRules)
    {
        $this->_stylesRules = $stylesRules;
    }

**Comment by mikehaertl** [comment]
@AirSeeker Hmm, if we use `fromArray()` to set cell values, we'd lose the extra features we have in `renderRow()`. I'm worried, that this could confuse developers as it makes the class behave quite differently from the default. In your case wouldn't it make more sense to use PHPOffice without our library here? If really, we should maybe create a dedicated sheet class for this.

Regarding `styleRules`: This looks like a good idea. It would be a simpler alternative to `callbacks`. I'd simply call it `styles`, though - unless you see a reason not to do so.

**Comment by AirSeeker** [comment]
@mikehaertl, I agree with you will use PHPOffice without your library. About styles: i think its will be more simple and faster then callbacks. But for backward support callbacks should also presents.

**Comment by mikehaertl** [comment]
> About styles: i think its will be more simple and faster then callbacks. But for backward support callbacks should also presents.

Agreed. So let's just implement a new `styles` property. I'll leave this open to track the changes/discussion.

**Comment by mikehaertl** [comment]
@AirSeeker Regaring the order: I would now apply the styles before rendering the rows. This way one could still override some specific styling in a callback. This is the reverse order than in your suggested implementation. Do you maybe see any problems here?

**Comment by AirSeeker** [comment]
@mikehaertl I see no problems there.

**Comment by mikehaertl** [comment]
@AirSeeker I've pushed an implementation but had no time to test it. Could you maybe help and check if it works as expected?

**Comment by AirSeeker** [comment]
@mikehaertl I tested it. Works as expected.

**Comment by mikehaertl** [comment]
Great, thanks. It's now in release 2.3.0.
