### ISSUE TITLE
how can export one file with multi sheets from an array data

### ISSUE THREAD

**Issue by hoangtuan136** [codemix/yii2-excelexport#16]
i have an array data got from database, like this: 
$array = [ 'sheet1'=>[1, 2, 3], 'sheet2'=>[4, 5, 6], 'sheet3'=>........ ]
how can export one excel file with multi sheet, each sheet is a item in the array above?

**Comment by mikehaertl** [comment]
It's all in the README. https://github.com/codemix/yii2-excelexport#raw-data

I can't help to to bring your array data into the right shape, though.
