### ISSUE TITLE
Can't Export to excel

### ISSUE THREAD

**Issue by khanfan** [codemix/yii2-excelexport#17]
I have problem with export to excel. It's show somthing. Please see sample below.
Sample
 |
 |
\/
" PKQ\#LG�D�X�[Content_Types].xml��MN�0���"�%nY ��vAa �(0����ؖg�w{&i�@�nbE�{��y��d۸l m�����X�(���)���F��;@1_�����c)j�x/%��E��y� �QĿi!��K�y3�J<���Z1�0?Y�L%zV c��Ib7�����a/l٥P1:�q�r��j��j0A����u�""���(� ���W�M��)Tj�({ܲ�>�O��,X٭���>B��~׭���Ӥ6�J=�oBZ����t��X4���Cg�,���QgmrL�ٯc�e��t�� Z�?����hPv��±��u�j���R������}�Cv��PKQ\#L�78�K_rels/.rels���j�0��{ �{���1F�^ʠ�2��l�$���-}�y����Î��O��v�y�;�؋Ӱ.JP��޵^�����Yű�3G�Ww�g)���>�qQC��D�� "

**Comment by mikehaertl** [comment]
Sorry, I can not help you with an error report like this. Please provide a full simplified (!!) example, to reproduce the problem.
