### ISSUE TITLE
Please fix your composer as your PHPExcel is not compatible with 1.9

### ISSUE THREAD

**Issue by mithun12000** [codemix/yii2-excelexport#2]
Hi there,

can you please fix your composer?

regards
Mithun Mandal

**Comment by mikehaertl** [comment]
Can you give some more details please? I'm not aware of any changes in the `composer.json` schema in 1.9

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback. I can't see what's wrong with the `composer.json`. If I'm missing something, please add a comment and point me to the fix.
