### ISSUE TITLE
Error In MSSQL Server

### ISSUE THREAD

**Issue by MasoudZeini** [codemix/yii2-excelexport#20]
when export and use mssql server db this error show up : 

SQLSTATE[IMSSP]: There are no more rows in the active result set. Since this result set is not scrollable, no more data may be retrieved.

**Comment by mikehaertl** [comment]
I'm not sure if this is a problem of our library here. It probably has to do with the way we loop over the results, using [Query::each()](http://www.yiiframework.com/doc-2.0/yii-db-query.html#each()-detail): 

https://github.com/codemix/yii2-excelexport/blob/master/src/ActiveExcelSheet.php#L56

So could you check if [batched queries](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html#batch-query) work at all in your setup? If not you should rather open an issue with yii2.

**Comment by mikehaertl** [comment]
It seems, that it's a known bug: https://github.com/yiisoft/yii2/issues/10023

As a workaround you could extend your own class from `ActiveExcelSheet` and overwrite `getData()` there. Just keep in mind that you may run into problems with large result sets if you don't use batch queries.
