### ISSUE TITLE
Package phpoffice/phpexcel is abandoned

### ISSUE THREAD

**Issue by max-dreamsoft** [codemix/yii2-excelexport#24]
> Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

Are there plans to migrate to phpspreadsheet?

**Comment by mikehaertl** [comment]
Yes, but I had no time to do so yet. The old package should still work fine, though.

**Comment by nollm** [comment]
Maybe this could help https://github.com/PHPOffice/PhpSpreadsheet/blob/master/docs/topics/migration-from-PHPExcel.md

**Comment by mikehaertl** [comment]
For those waiting for this issue: I don't think that I'll ever find time to do the migration as I no longer use this library myself. The migration should be straightforward though. So maybe someone wants to volunteer?

**Comment by mikehaertl** [comment]
Just released 2.8.0 which uses PhpSpreadsheet now (thanks to @devOp1)
