### ISSUE TITLE
"Raw data" example crashes

### ISSUE THREAD

**Issue by max-dreamsoft** [codemix/yii2-excelexport#25]
Just copy-pasted "Raw data" example from README.md. Execution result was:

> Invalid argument supplied for foreach()
> 1. in sitedir/vendor/codemix/yii2-excelexport/src/ExcelSheet.php at line 250
> 2. in sitedir/vendor/codemix/yii2-excelexport/src/ExcelFile.php at line 141 – codemix\excelexport\ExcelSheet::render()
> 3. in sitedir/vendor/codemix/yii2-excelexport/src/ExcelFile.php at line 154 – codemix\excelexport\ExcelFile::createSheets()
> 4. in sitedir/vendor/codemix/yii2-excelexport/src/ExcelFile.php at line 98 – codemix\excelexport\ExcelFile::createFile()
> 5. in sitedir/controllers/TestController.php at line 137 – codemix\excelexport\ExcelFile::saveAs('filename' => ''test.xlsx'')

**Comment by mikehaertl** [comment]
@max-dreamsoft Did you find the problem? What was it?
