### ISSUE TITLE
getSheet(1) returns "Your requested sheet index: 1 is out of bounds"

### ISSUE THREAD

**Issue by MPTCrystal** [codemix/yii2-excelexport#28]
I am creating a 2 sheet Excel file which exports correctly. I can use getSheet(0) to setAutoSize() on columns on the first column, but not column 1.

The code to create the Excel file (as Raw data) is...

$sheets = array();

$sheet1 = array();
$data1 = array();
$sheet1['titles']=['Name'];
$data1[] = ['A long name'];
$sheet1['data']=$data1;

$sheets['First']=$sheet1;
$sheets['Second']=$sheet1;

$file = \Yii::createObject([
    'class' => 'codemix\excelexport\ExcelFile',
    'sheets' => $sheets
]);

And the code to set the column width is...

$file->getWorkbook()->getSheet(0)->getColumnDimension('A')->setAutoSize(true); // Works
$file->getWorkbook()->getSheet(1)->getColumnDimension('A')->setAutoSize(true); // Causes error.

**Comment by mikehaertl** [comment]
What error?

**Comment by mikehaertl** [comment]
Ok, the error is in the title. I think you need to call `createSheets()` before you can access all sheets. Can you try that? I should update the README to add a note about this.

**Comment by MPTCrystal** [comment]
The full error is ... Your requested sheet index: 1 is out of bounds. The actual number of sheets is 1.

It is thrown by ... phpoffice\phpexcel\Classes\PHPExcel.php ... line 577.

**Comment by MPTCrystal** [comment]
That worked.

I had noted the createSheets() function in ExcelFile.php but assumed that because setAutoSize(true) worked for the first sheet that both sheets must exist.

**Comment by mikehaertl** [comment]
I think there's already 1 sheet created by default. I'll add something to the README. Thanks for reporting.
