### ISSUE TITLE
How to set all cells in whole workbook to autosize?

### ISSUE THREAD

**Issue by shabaz-ejaz** [codemix/yii2-excelexport#30]
I believe its possible to do this:

```
$file->getWorkbook()->getSheet(0)->getColumnDimension('A')->setWidth("35");
$file->getWorkbook()->getSheet(0)->getColumnDimension('B')->setAutoSize(true);
```

However is it possible to set all cells within a sheet to auto size?

**Comment by shabaz-ejaz** [comment]
So I can do it like this:

```
for ($i = 'A'; $i !=$file->getWorkbook()->getSheet(0)->getHighestColumn(); $i++) {
     $file->getWorkbook()->getSheet(0)->getColumnDimension($i)->setAutoSize(TRUE);
 }
```

This will loop through all columns in sheet 0 and will autosize them.

A more elegant solution would be appreciated however.

**Comment by mikehaertl** [comment]
I don't think we will add something here. I want to avoid adding to much styling related code as our library is really more focussed on the data. And there are too many other things around styling.

As you have access to the lower level PHPExcel objects you still can achieve almost everything as your example shows.
