### ISSUE TITLE
The file is corrupt and therefore cannot be opened. LibreOffice can try to repair the file.

### ISSUE THREAD

**Issue by AndreiSB** [codemix/yii2-excelexport#31]
If $file->saveAs(), it opens,
If  $file->send(), it does not open.
The file is corrupt and therefore cannot be opened. LibreOffice can try to repair the file.

**Comment by mikehaertl** [comment]
Do you happen to have automatic gzip compression enabled in your webserver? We have a similar issue and some workarounds here: https://github.com/mikehaertl/phpwkhtmltopdf/issues/270

Best would be, if you could disable compression for certain file types.

**Comment by AndreiSB** [comment]
Good afternoon.
I sent my script to the hosting (hc.ru). And it works on hosting without errors.
The problem is only on my localhost.
Thank you for support!


>Воскресенье, 30 сентября 2018, 10:51 +03:00 от Michael Härtl <notifications@github.com>:
>
>Do you happen to have automatic gzip compression enabled in your webserver? We have a similar issue and some workarounds here:  mikehaertl/phpwkhtmltopdf#270
>Best would be, if you could disable compression for certain file types.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
bogapov andrey
