### ISSUE TITLE
Character encoiding issue on server

### ISSUE THREAD

**Issue by ankittechnosoft** [codemix/yii2-excelexport#34]
The excel file has been exported on my localhost successfully, but its not working on server. On server, a corrupted excel sheet is getting generated with character encoding problem. I am simply exporting with this line of code.
$file = \Yii::createObject([
                'class' => 'codemix\excelexport\ExcelFile',
                'sheets' => [
                    $sheetTitle => [   // Name of the excel sheet
                        'data' => $exportData,
                        'titles' => $titles,
                    ]
                ]
            ]);
            $file->send($sheetTitle.'.xlsx');
            exit;

I think there is some misconfiguration on server, but not sure what the problem is. I have PHP7.2 installed on my server.

Below is the output that is being generated when i export file.

PK�mrNG�D�X�[Content_Types].xml��MN�0��"�%nY ��vAa �(0��ؖg�w{&i�@�nbE�{��y��d۸l
--
m�����X�(���)���F��;@1_�����c)j�x/%��E��y�
�QĿi!��K�y3�J<���Z1�0?Y�L%zV
c��Ib7����a/l٥P1:�q�r��j��j0A����u�""���(�	���W�M��)Tj�({ܲ�>�O��,X٭���>B��~׭���Ӥ6�J=�oBZ����t��X4��Cg�,���QgmrL�ٯc�e��t�	Z�?����hPv��±�u�j�<R�����}�Cv��PK�mrN�78�K_rels/.rels���j�0��{
�{���1F�^ʠ�2��l�$���-}�y����Î��O��v�y�;�؋Ӱ.JP��޵^�����Yű�3G�Ww�g)���>�qQC��D���b!�]�i$L��3����2n���oT�:Z
�h����[��4�ი��]��yN�,ە�>�>�j

Thanks

**Comment by mikehaertl** [comment]
Are you sure, that your `$exportData` content has the correct character encoding? Also do you maybe have a compression module installed in your server software (Nginx, Apache, ...)?

**Comment by mikehaertl** [comment]
Actually I'm pretty sure, that you have some sort of compression module running: The first two characters in your content are `PK` and this is usually the first 2 bytes of a ZIP file: https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html

It's basically the same bug as described here (it's using the same base library https://github.com/mikehaertl/php-tmpfile): https://github.com/mikehaertl/phpwkhtmltopdf/issues/270. You can try to exclude certain URLs from compression.

**Comment by mikehaertl** [comment]
@ankittechnosoft Any news here? Did you check if a compression module is enabled in your webserver?

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback. Feel free to add another comment if you have any updates.
