### ISSUE TITLE
Can this be used to get specific rows from a table?

### ISSUE THREAD

**Issue by harsh-growfitter** [codemix/yii2-excelexport#36]
I am confused where do I write this code??
In controller action or view?(when will this be triggered)
Can this be used to export specific data from database based on my query?
Can someone please clarify

**Comment by mikehaertl** [comment]
I'm sorry if this sounds harsh - but this is not the place for this kind of questions. Issues are to report bugs. That being said: It's up to you where you want to put the relevant code. In my projects I created for example a `models/exports/UserExport.php`. Use your imagination what's a good way to organize things there. I can not help you with that.
