### ISSUE TITLE
not redirecting

### ISSUE THREAD

**Issue by siromidz** [codemix/yii2-excelexport#37]
i want to export some data as a file and then redirect to the main page:

$file = \Yii::createObject([
                    'class' => 'codemix\excelexport\ExcelFile',
                    'sheets' => [

                        'sheet1' => [
                            'data' => $active_codes,
                            
                            'titles' => [
                                'Activation Code'
                            ],
                        ],
                    ]
                ]);

                $file->send('export.xlsx');
                
                return $this->redirect(['index']);

file is downloaded, but after that, page is not redirected.

**Comment by mikehaertl** [comment]
That's just not possible with HTTP. You can either send a file as response or a redirect.
