### ISSUE TITLE
Add custom column to file

### ISSUE THREAD

**Issue by ghost** [codemix/yii2-excelexport#38]
I want to understand how i can add some attribute to excell file, which out of columns from db. I have db with columns: ID, NAME, CAR. So when i create a file this columns will be my attributes. And i want to add some attribute, like PRICE, but it just a $price = "price"; . Help please

**Comment by mikehaertl** [comment]
You should try to include this column in your query result. Did you try something like this:

```php
$query = Car::find()
    ->select(['ID', 'NAME', 'CAR', "'price' as price"]);
```

To make this work you may need a `public $price` in your ActiveRecord class. If there already is a `price` column you can name it whatever you want. In `attributeLabels()` you can assign it a label.

**Comment by ghost** [comment]
thanks, your advice helped me
