### ISSUE TITLE
Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by alejosv** [codemix/yii2-excelexport#41]
Error in `vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell/DefaultValueBinder.php`

    public static function dataTypeForValue($pValue = null)
    {
        // Match the value against a few data types
        if ($pValue === null) {
            return PHPExcel_Cell_DataType::TYPE_NULL;
        } elseif ($pValue === '') {
            return PHPExcel_Cell_DataType::TYPE_STRING;
        } elseif ($pValue instanceof PHPExcel_RichText) {
            return PHPExcel_Cell_DataType::TYPE_INLINE;
        } elseif ($pValue{0} === '=' && strlen($pValue) > 1) {
            return PHPExcel_Cell_DataType::TYPE_FORMULA;
        } elseif (is_bool($pValue)) {
            return PHPExcel_Cell_DataType::TYPE_BOOL;
        } elseif (is_float($pValue) || is_int($pValue)) {
            return PHPExcel_Cell_DataType::TYPE_NUMERIC;
        } elseif (preg_match('/^[\+\-]?([0-9]+\\.?[0-9]*|[0-9]*\\.?[0-9]+)([Ee][\-\+]?[0-2]?\d{1,3})?$/', $pValue)) {
            $tValue = ltrim($pValue, '+-');
            if (is_string($pValue) && $tValue{0} === '0' && strlen($tValue) > 1 && $tValue{1} !== '.') {
                return PHPExcel_Cell_DataType::TYPE_STRING;

Specifictly in:

        } elseif ($pValue{0} === '=' && strlen($pValue) > 1) {

I suppose this error is phpoffice package.

**Comment by mikehaertl** [comment]
Do you have a full stack trace or something? Also a simple example to reproduce the issue would help.

**Comment by alejosv** [comment]
Full stack trace 

 ```
PHP Notice – yii\base\ErrorException
Trying to access array offset on value of type int
```

    1. in /lxcshared/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell/DefaultValueBinder.php at line 82
    73747576777879808182838485868788899091

        public static function dataTypeForValue($pValue = null)
        {
            // Match the value against a few data types
            if ($pValue === null) {
                return PHPExcel_Cell_DataType::TYPE_NULL;
            } elseif ($pValue === '') {
                return PHPExcel_Cell_DataType::TYPE_STRING;
            } elseif ($pValue instanceof PHPExcel_RichText) {
                return PHPExcel_Cell_DataType::TYPE_INLINE;
            } elseif ($pValue{0} === '=' && strlen($pValue) > 1) {
                return PHPExcel_Cell_DataType::TYPE_FORMULA;
            } elseif (is_bool($pValue)) {
                return PHPExcel_Cell_DataType::TYPE_BOOL;
            } elseif (is_float($pValue) || is_int($pValue)) {
                return PHPExcel_Cell_DataType::TYPE_NUMERIC;
            } elseif (preg_match('/^[\+\-]?([0-9]+\\.?[0-9]*|[0-9]*\\.?[0-9]+)([Ee][\-\+]?[0-2]?\d{1,3})?$/', $pValue)) {
                $tValue = ltrim($pValue, '+-');
                if (is_string($pValue) && $tValue{0} === '0' && strlen($tValue) > 1 && $tValue{1} !== '.') {
                    return PHPExcel_Cell_DataType::TYPE_STRING;

    2. in /lxcshared/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell/DefaultValueBinder.php at line 82 – yii\web\ErrorHandler::handleError()
    76777879808182838485868788

            if ($pValue === null) {
                return PHPExcel_Cell_DataType::TYPE_NULL;
            } elseif ($pValue === '') {
                return PHPExcel_Cell_DataType::TYPE_STRING;
            } elseif ($pValue instanceof PHPExcel_RichText) {
                return PHPExcel_Cell_DataType::TYPE_INLINE;
            } elseif ($pValue{0} === '=' && strlen($pValue) > 1) {
                return PHPExcel_Cell_DataType::TYPE_FORMULA;
            } elseif (is_bool($pValue)) {
                return PHPExcel_Cell_DataType::TYPE_BOOL;
            } elseif (is_float($pValue) || is_int($pValue)) {
                return PHPExcel_Cell_DataType::TYPE_NUMERIC;
            } elseif (preg_match('/^[\+\-]?([0-9]+\\.?[0-9]*|[0-9]*\\.?[0-9]+)([Ee][\-\+]?[0-2]?\d{1,3})?$/', $pValue)) {

    3. in /lxcshared/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell/DefaultValueBinder.php at line 61 – PHPExcel_Cell_DefaultValueBinder::dataTypeForValue()
    55565758596061626364656667

                } elseif (!($value instanceof PHPExcel_RichText)) {
                    $value = (string) $value;
                }
            }
     
            // Set value explicit
            $cell->setValueExplicit($value, self::dataTypeForValue($value));
     
            // Done!
            return true;
        }
     
        /**

    4. in /lxcshared/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php at line 206 – PHPExcel_Cell_DefaultValueBinder::bindValue()
    200201202203204205206207208209210211212

         *    @param    mixed    $pValue                    Value
         *    @return    PHPExcel_Cell
         *    @throws    PHPExcel_Exception
         */
        public function setValue($pValue = null)
        {
            if (!self::getValueBinder()->bindValue($this, $pValue)) {
                throw new PHPExcel_Exception("Value could not be bound to cell.");
            }
            return $this;
        }
     
        /**

    5. in /lxcshared/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php at line 1100 – PHPExcel_Cell::setValue()
    1094109510961097109810991100110111021103110411051106

         * @param mixed $pValue Value of the cell
         * @param bool $returnCell Return the worksheet (false, default) or the cell (true)
         * @return PHPExcel_Worksheet|PHPExcel_Cell    Depending on the last parameter being specified
         */
        public function setCellValueByColumnAndRow($pColumn = 0, $pRow = 1, $pValue = null, $returnCell = false)
        {
            $cell = $this->getCellByColumnAndRow($pColumn, $pRow)->setValue($pValue);
            return ($returnCell) ? $cell : $this;
        }
     
        /**
         * Set a cell value
         *

    6. in /lxcshared/app/vendor/codemix/yii2-excelexport/src/ExcelSheet.php at line 275 – PHPExcel_Worksheet::setCellValueByColumnAndRow()
    269270271272273274275276277278279280281

                if (isset($formatters[$col]) && is_callable($formatters[$col])) {
                    $value = call_user_func($formatters[$col], $value, $row, $data);
                }
                if (isset($types[$col])) {
                    $this->_sheet->setCellValueExplicitByColumnAndRow($col, $row, $value, $types[$col]);
                } else {
                    $this->_sheet->setCellValueByColumnAndRow($col, $row, $value);
                }
                if (isset($formats[$col])) {
                    $this->_sheet
                        ->getStyleByColumnAndRow($col, $row)
                        ->getNumberFormat()
                        ->setFormatCode($formats[$col]);

    7. in /lxcshared/app/vendor/codemix/yii2-excelexport/src/ActiveExcelSheet.php at line 304 – codemix\excelexport\ActiveExcelSheet::renderRow()
    298299300301302303304305306307308309310

         */
        protected function renderRow($data, $row, $formats, $formatters, $callbacks, $types)
        {
            $values = array_map(function ($attr) use ($data) {
                return ArrayHelper::getValue($data, $attr);
            }, $this->getAttributes());
            return parent::renderRow($values, $row, $formats, $formatters, $callbacks, $types);
        }
     
        /**
         * Convert a datetime to the right excel timestamp
         *
         * This method will use [[\yii\i18n\Formatter::defaultTimeZone]] and

    8. in /lxcshared/app/vendor/codemix/yii2-excelexport/src/ExcelSheet.php at line 251 – codemix\excelexport\ActiveExcelSheet::renderRow()
    245246247248249250251252253254255256257

            $formats = $this->normalizeIndex($this->getFormats());
            $formatters = $this->normalizeIndex($this->getFormatters());
            $callbacks = $this->normalizeIndex($this->getCallbacks());
            $types = $this->normalizeIndex($this->getTypes());
     
            foreach ($this->getData() as $data) {
                $this->renderRow($data, $this->_row++, $formats, $formatters, $callbacks, $types);
            }
        }
     
        /**
         * Render a single row
         *

    9. in /lxcshared/app/vendor/codemix/yii2-excelexport/src/ExcelSheet.php at line 194 – codemix\excelexport\ActiveExcelSheet::renderRows()
    188189190191192193194195196197198199200

        public function render()
        {
            $this->beforeRender();
            $this->_row = $this->startRow;
            $this->renderStyles();
            $this->renderTitle();
            $this->renderRows();
            $this->trigger(self::EVENT_AFTER_RENDER);
        }
     
        /**
         * Trigger the [[EVENT_BEFORE_RENDER]] event
         */

    10. in /lxcshared/app/vendor/codemix/yii2-excelexport/src/ExcelFile.php at line 141 – codemix\excelexport\ActiveExcelSheet::render()
    135136137138139140141142143144145146147

                    }
                    $sheet = ($i === 0) ?
                        $workbook->getActiveSheet() : $workbook->createSheet();
                    if (is_string($title)) {
                        $sheet->setTitle($title);
                    }
                    Yii::createObject($config, [$sheet])->render();
                    $i++;
                }
                $this->_sheetsCreated = true;
            }
        }
     

    11. in /lxcshared/app/vendor/codemix/yii2-excelexport/src/ExcelFile.php at line 154 – codemix\excelexport\ExcelFile::createSheets()
    148149150151152153154155156157158159

        /**
         * Create the Excel file and save it to the temp file
         */
        protected function createFile()
        {
            if (!$this->_fileCreated) {
                $this->createSheets();
                $this->getWriter()->save((string) $this->getTmpFile());
                $this->_fileCreated = true;
            }
        }
    }

    12. in /lxcshared/app/vendor/codemix/yii2-excelexport/src/ExcelFile.php at line 114 – codemix\excelexport\ExcelFile::createFile()
    108109110111112113114115116117118119120

         * filename is present.
         * @param string $contentType the Content-Type header. Default is
         * 'application/vnd.ms-excel'.
         */
        public function send($filename = null, $inline = false, $contentType =  'application/vnd.ms-excel')
        {
            $this->createFile();
            $this->getTmpFile()->send($filename, $contentType, $inline);
        }
     
        /**
         * Create the Excel sheets if they were not created yet
         */

    13. in /lxcshared/app/controllers/ClientsController.php at line 553 – codemix\excelexport\ExcelFile::send()
    547548549550551552553554555556557558559

                        'query' => ClientsDetails::find()
                    ]
                ]
            ]);
     
            $fileName = 'clients_dbname_' . date('Y-m-d_H:i') . '.xlsx';
            $file->send($fileName);
     
            // $sql = "SELECT * FROM clients_details";
     
            // Generamos los archivos XLS
            /* $excelReport = new Spreadsheet([
                'dataProvider' => new SqlDataProvider([

    14. in /lxcshared/app/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – app\controllers\ClientsController::actionDownloadXls()
    15. in /lxcshared/app/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array:{/lxcshared/app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
    16. in /lxcshared/app/vendor/yiisoft/yii2/base/Controller.php at line 180 – yii\base\InlineAction::runWithParams()
    17. in /lxcshared/app/vendor/yiisoft/yii2/base/Module.php at line 528 – app\controllers\ClientsController::runAction()
    18. in /lxcshared/app/vendor/yiisoft/yii2/web/Application.php at line 103 – yii\web\Application::runAction()
    19. in /lxcshared/app/vendor/yiisoft/yii2/base/Application.php at line 386 – yii\web\Application::handleRequest()
    20. in /lxcshared/app/web/index.php at line 13 – yii\web\Application::run()

Simple example:

        $file = \Yii::createObject([
            'class' => 'codemix\excelexport\ExcelFile',
            'sheets' => [
                'Clients' => [
                    'class' => 'codemix\excelexport\ActiveExcelSheet',
                    'query' => ClientsDetails::find()
                ]
            ]
        ]);
        
        $fileName = 'clients_dbname_' . date('Y-m-d_H:i') . '.xlsx';
        $file->send($fileName);

**Comment by mikehaertl** [comment]
Can you show the `CREATE` statement for your ClientsDetail table?

Also if you look at the data in that table, is there something that looks suspicious? Or a special data type?

**Comment by alejosv** [comment]
This model is based in a view, and I don't see special data type

![image](https://user-images.githubusercontent.com/14202497/97350853-9e7a4780-1856-11eb-9ff6-43816ec483ca.png)
![image](https://user-images.githubusercontent.com/14202497/97350908-b0f48100-1856-11eb-8d60-10b547d04002.png)

**Comment by mikehaertl** [comment]
Ok, some random thoughts:

 * The error is `Trying to access array offset on value of type int` so the problematic value must be an integer
 * Yii's ActiveRecord usually converts integers to strings so an integer should not happen
 * Maybe it's a problem with Yii and your view and it can't detect the data types

What you could try:

 * Insert some debugging lines e.g. in `vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell/DefaultValueBinder::dataTypeForValue()` (Line 75) something like
  ```
  if (is_int($pValue)) {
    echo $pValue;
    exit;
  }
 ```
* You could also try to define explicit types in your sheet configuration. Something like:

```
'query' => ..., 
'types' => [
    'B' => \PHPExcel_Cell_DataType::TYPE_NUMERIC,
],
```
* If nothing helps, try with another, fresh DB view that only has the first column, then the first 2 columns etc. and see at which column it breaks

**Comment by alejosv** [comment]
@mikehaertl  Apparently exists a logical error in the `dataTypeForValue`, I puted the condition: `elseif ($pValue{0} === '=' && strlen($pValue) > 1)` as last condition and the error desapere. 

This condition evaluate if exists a formula into a cell, why should by in the last condition? because this method should evaluate values first and next formulas, at leats this would make better sense.

**Comment by alejosv** [comment]
Even worse, the phpoffice/phpexcel package is deprecated

**Comment by alejosv** [comment]
The [official and maintained package](https://github.com/PHPOffice/PhpSpreadsheet) change the way to evaluate the cells values

https://github.com/PHPOffice/PhpSpreadsheet/blob/7b1957f996be566766aec370197dfacdd898592b/src/PhpSpreadsheet/Cell/DefaultValueBinder.php#L47-L81

**Comment by mikehaertl** [comment]
> Even worse, the phpoffice/phpexcel package is deprecated

I know - but I had no time to rewrite this library for the latest version. Also in the most cases it still works for me. I could maybe check if we can fix something. But then we would really need a full simple (!) example including everything: DB tables + views + data, preferrably for MySQL. Something must be special about your case.

Not sure if it's worth the effort, though and also can't promise that I would find time to look into it.
