### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by JobirYusupov** [codemix/yii2-excelexport#43]
{
    "name": "PHP Compile Error",
    "message": "Array and string offset access syntax with curly braces is no longer supported",
    "code": 64,
    "type": "yii\\base\\ErrorException",
    "file": "/home/netkostu/public_html/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/String.php",
    "line": 529,
    "stack-trace": [
        "#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()",
        "#1 {main}"
    ]
}

**Comment by mikehaertl** [comment]
This is a problem with PHPExcel and there's already an issue to upgrade to a newer version: #24. Unfortunately I don't think that I'll ever find time to do the upgrade as I no longer use this library myself.

Closing this a duplicate.
