### ISSUE TITLE
I can't install this components via composer

### ISSUE THREAD

**Issue by ghost** [codemix/yii2-excelexport#5]
I got this following error message when I tried to install it via composer

[InvalidArgumentException]  
  Could not find package yii.bat at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

![screenshot from 2016-09-17 23 02 52](https://cloud.githubusercontent.com/assets/11723160/18609374/f1ea7226-7d2a-11e6-835e-0e2cd65754f9.png)
How do I suppose to install it ?

**Comment by mikehaertl** [comment]
I can not reproduce this. Do you maybe have some special global composer config in your `~/.composer/composer.conf`?

You should actually also first install a yii2 application and then require our package from there. But I've also tried with an empty directory and it works (even if it doesn't make much sense). 

```
$ composer require codemix/yii2-excelexport *
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing yiisoft/yii2-composer (2.0.4)               
    Loading from cache

  - Installing phpoffice/phpexcel (1.8.1)
    Loading from cache

  - Installing mikehaertl/php-tmpfile (1.1.0)
    Loading from cache

  - Installing bower-asset/jquery (2.2.4)
    Loading from cache

  - Installing bower-asset/yii2-pjax (v2.0.6)
    Loading from cache

  - Installing bower-asset/punycode (v1.3.2)
    Loading from cache

  - Installing bower-asset/jquery.inputmask (3.2.7)
    Loading from cache

  - Installing cebe/markdown (1.1.1)
    Loading from cache

  - Installing ezyang/htmlpurifier (v4.8.0)
    Loading from cache

  - Installing yiisoft/yii2 (2.0.9)
    Loading from cache

  - Installing codemix/yii2-excelexport (1.0.1)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by Sandalf** [comment]
If anyone else still gets the same problem try running:

`composer require codemix/yii2-excelexport --dev`

This worked for me.
