### ISSUE TITLE
Write based common array

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [codemix/yii2-excelexport#6]
Can you provide me how to use this awesome extension if I have an array like this 👍 
    `    Array
        (
        [0] => Array
        (
            [karyawan_id] => 2
            [nama_karyawan] => Rizal
            [nama_item] => Gunting Wanita
            [harga] => 75,000.00
            [persen_komisi] => 40
            [amount_komisi] => 30,000.00
            [counting] => 2
            [total_item] => 150000
            [total_komisi_karyawan] => 60,000.00
            [total_omset] => 150,000.00
        )

    [1] => Array
        (
            [karyawan_id] => 2
            [nama_karyawan] => Rizal
            [nama_item] => Gunting Pria
            [harga] => 70,000.00
            [persen_komisi] => 50
            [amount_komisi] => 35,000.00
            [counting] => 
            [total_item] => 
            [total_komisi_karyawan] => 
            [total_omset] => 
        )

    [2] => Array
        (
            [karyawan_id] => 2
            [nama_karyawan] => Rizal
            [nama_item] => Gunting Poni
            [harga] => 20,000.00
            [persen_komisi] => 80
            [amount_komisi] => 16,000.00
            [counting] => 1
            [total_item] => 20000
            [total_komisi_karyawan] => 16,000.00
            [total_omset] => 20,000.00
        )

)`

For the help, it so appreciated

**Comment by mikehaertl** [comment]
The readme shows, how to use an array: https://github.com/codemix/yii2-excelexport#raw-data
