### ISSUE TITLE
Cant create excel from data

### ISSUE THREAD

**Issue by justixLoL** [codemix/yii2-excelexport#8]
I try put data that i already have after db query (because if i put Query instead of data - it does not work - it 
 does not calling '->all()' in your Sheet) as in your example.

```
$rows = TableName::find()->where("condition")->all();
$file = \Yii::createObject([
                'class' => 'codemix\excelexport\ExcelFile',
                'sheets' => [
                    'Users' => [
                        'data' => $rows],
                ]
            ]);
$file->saveAs($fileName);
```

And it throw error. What i do wrong?

**Comment by mikehaertl** [comment]
If you provide the sheet data in `data` it should be an array of raw data, not an array of ActiveRecords as returned by `all()`. If you want to use ActiveRecords you should not call `all()` and provide the query in `query`:

```
'query' => TableName::find()->where("..."),
```
